---
version: '2'
services:
  mysql57:
    # For Apple Silicon / ARM
    # image: biarms/mysql:5.7
    image: mysql:5.7
    command: [ "--server-id=1", "--log-bin=/var/lib/mysql/mysql-bin.log", "--binlog-format=row"]
    networks:
      default:
        aliases:
          - mysql57
    environment:
      MYSQL_ROOT_PASSWORD: numtel

  mysql81:
    image: mysql:8.1
    command: [ "--server-id=1", "--log-bin=/var/lib/mysql/mysql-bin.log", "--binlog-format=row", "--binlog-transaction-compression=OFF"]
    networks:
      default:
        aliases:
          - mysql81
    environment:
      MYSQL_ROOT_PASSWORD: numtel

  mysql82:
    image: mysql:8.2
    command: [ "--server-id=1", "--log-bin=/var/lib/mysql/mysql-bin.log", "--binlog-format=row", "--binlog-transaction-compression=ON", "--binlog-transaction-compression-level-zstd=22" ]
    networks:
      default:
        aliases:
          - mysql82
    environment:
      MYSQL_ROOT_PASSWORD: numtel
